name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.26

      - name: Set version env
        run: |
          VERSION=${GITHUB_REF##*/} 
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Build binaries
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          FILENAME=gt-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            FILENAME="${FILENAME}.exe"
          fi
          go build -o dist/$FILENAME
          sha256sum dist/$FILENAME > dist/$FILENAME.sha256

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }} - TOTP in Go.
          generate_release_notes: true
          body: ${{ steps.changelog.outputs.changelog }}
          # body: "Binary releases for version ${{ github.ref_name }}"
          files: dist/*
          fail_on_unmatched_files: true
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
